### ISSUE TITLE
Calibration is slightly inaccurate

### ISSUE THREAD

**Issue by WillB97** [srobo/sr-robot3-j5#49]
A team has found that the vision measures over by about 10% using a C270. After this competition year we should do some new calibrations at longer distances to make this more accurate.
![image](https://user-images.githubusercontent.com/10937272/155404101-2c0c19a5-6bd3-433d-b3e3-939de5a7e178.png)

**Comment by trickeydan** [comment]
@WillB97 Is this still an issue?

**Comment by WillB97** [comment]
I am not aware that anything has changed on this front.

**Comment by trickeydan** [comment]
@RealOrangeOne Please would you be able to take this on? 🙏

**Comment by RealOrangeOne** [comment]
I believe this is still an issue, yes. I think the cause of the issue is slightly incorrect calibrations. I'll need to have another look at the correct process for taking calibrations, but then yes I should be able to give this a look. 5-7% isn't much, so I definitely wouldn't consider this blocking.

**Comment by trickeydan** [comment]
Hi @RealOrangeOne, Have you had chance to make any progress on this?

**Comment by RealOrangeOne** [comment]
I haven't I'm afraid, no. My suspicion is it's an issue with the calibrations, but without a C270 to hand I can't be sure. I'm planning on trying to trying to generate good calibrations with a webcam I have, and seeing how accurate I can get them.

Personally, as this is just going to be a calibration update, I wouldn't consider this a blocker for SR2023, mostly as I can't promise I'll be able to get a (reliable) update out in a reasonable time for testing before kickstart.

**Comment by trickeydan** [comment]
Fixed by #89
