### ISSUE TITLE
Add property to determine if the code is in the simulator or not

### ISSUE THREAD

**Issue by trickeydan** [srobo/sr-robot3-j5#75]
Requested in Discord

**Comment by PeterJCLaw** [comment]
Depending somewhat on how much we want this to be the canonical approach, this is already possible fairly easily. There are various properties on `Robot.metadata` which are hard-coded to empty or `None` values which will be non-empty on the kits.

See https://github.com/srobo/competition-simulator/blob/master/modules/sr/robot3/metadata.py
